uom_translations = {
                    'BOX': 'product.product_cwa_box', 
                    'DISP': 'product.product_cwa_disp', 
                    'BAR': 'product.product_cwa_bar', 
                    'CRT': 'product.product_cwa_crt', 
                    'FOLIE': 'product.product_cwa_folie', 
                    'PCS': 'product.product_cwa_pcs', 
                    'BLIK': 'product.product_cwa_blik', 
                    '300 M': 'product.product_cwa_300ml', 
                    'BACK': 'product.product_cwa_back', 
                    'BAG': 'product.product_cwa_bag', 
                    'AGF LOS': 'product.product_cwa_agf los', 
                    '6-PACK': 'product.product_cwa_6-pack', 
                    'KUIPJE': 'product.product_cwa_kuipje', 
                    'NET': 'product.product_cwa_Net', 
                    'PAK': 'product.product_cwa_pak', 
                    'BAK': 'product.product_cwa_bak', 
                    'ROLLER': 'product.product_cwa_roller', 
                    'DOOS': 'product.product_cwa_doos', 
                    'STUKS': 'product.product_cwa_stuks', 
                    'BOTTL': 'product.product_cwa_bottl', 
                    'FLESJE': 'product.product_cwa_flesje', 
                    '20': 'product.product_cwa_20', 
                    'AGF VERPAKT': 'product.product_cwa_agf verpakt', 
                    'TAS': 'product.product_cwa_Tas', 
                    'BOEKJE': 'product.product_cwa_boekje', 
                    'BUS': 'product.product_cwa_bus', 
                    'POT': 'product.product_cwa_pot', 
                    'TETRA': 'product.product_cwa_tetra', 
                    'METER': 'product.product_uom_meter', 
                    '1': 'product.product_cwa_1',
                    'PC': 'product.product_cwa_pc', 
                    'REEP': 'product.product_cwa_reep', 
                    'GRAM': 'product.product_cwa_uom_g', 
                    'PAPIER': 'product.product_cwa_papier', 
                    'STUK': 'product.product_cwa_stuk', 
                    'EMMER': 'product.product_cwa_emmer', 
                    'SCHAALTJE': 'product.product_cwa_schaaltje', 
                    'SLANG': 'product.product_cwa_slang', 
                    'BRUSH': 'product.product_cwa_brush', 
                    'ZAK': 'product.product_cwa_zak', 
                    'BOS': 'product.product_cwa_bos', 
                    'KISTJE': 'product.product_cwa_Kistje', 
                    'DISPL': 'product.product_cwa_displ', 
                    'G': 'product.product_uom_gram', 
                    'GLAS': 'product.product_cwa_glas', 
                    'FLES': 'product.product_cwa_fles', 
                    'SETS': 'product.product_cwa_Sets', 
                    'GEEN VERPAKKING': 'product.product_cwa_geen verpakking', 
                    'BROOD': 'product.product_cwa_brood', 
                    'UNIT(S)': 'product.product_uom_unit', 
                    'CENTILITER': 'product.product_cwa_uom_cl', 
                    'POTJE': 'product.product_cwa_potje', 
                    'VERSTUIVER': 'product.product_cwa_verstuiver', 
                    'CELLO': 'product.product_cwa_cello', 
                    'SQCUP': 'product.product_cwa_SqCup', 
                    'DOOSJE': 'product.product_cwa_Doosje', 
                    'ROL': 'product.product_cwa_rol', 
                    'AL.PA': 'product.product_cwa_Al pa', 
                    'BUILTJE': 'product.product_cwa_uom_builtje', 
                    'BEKER': 'product.product_cwa_beker', 
                    'JUG': 'product.product_cwa_jug', 
                    '300ML': 'product.product_cwa_300ml', 
                    'BAGS': 'product.product_cwa_bags', 
                    'LITER': 'product.product_uom_litre', 
                    'KG': 'product.product_uom_kgm', 
                    'HELE KAAS': 'product.product_cwa_hele kaas', 
                    'TABLET': 'product.product_cwa_tablet', 
                    'LOS': 'product.product_cwa_Los', 
                    'PCSPA': 'product.product_cwa_pcspa', 
                    'ML': 'product.product_cwa_uom_Ml', 
                    'TUBE': 'product.product_cwa_tube', 
                    'AL BA': 'product.product_cwa_al ba', 
                    'POMPFLACON': 'product.product_cwa_pompflacon', 
                    'ZAKJE': 'product.product_cwa_zakje', 
                    'STICK': 'product.product_cwa_stick', 
                    'SET': 'product.product_cwa_Set', 
                    'WIKKEL': 'product.product_cwa_wikkel', 
                    'PACK': 'product.product_cwa_pack', 
                    'TRAY': 'product.product_cwa_tray', 
                    'CAN': 'product.product_cwa_Can',}

statiegeld_translations = { # 5, 0.25, 0.45, 0.08, 0.1, 0.6, 0.15, 0.4, 1.75
                           'NONE' : 0,
                           'None' : 0,
                           'False' : 0, 
                           '5' : "cwa_module.cwa_statiegeld_5",
                           '5.0' : "cwa_module.cwa_statiegeld_5",
                           '5.00' : "cwa_module.cwa_statiegeld_5",
                           '1.75' : "cwa_module.cwa_statiegeld_175",
                           '0.6' : "cwa_module.cwa_statiegeld_060",
                           '0.60' : "cwa_module.cwa_statiegeld_060",
                           '0.45' : "cwa_module.cwa_statiegeld_045",
                           '0.4' : "cwa_module.cwa_statiegeld_040",
                           '0.40' : "cwa_module.cwa_statiegeld_040",
                           '0.25' : "cwa_module.cwa_statiegeld_025",
                           '0.15' : "cwa_module.cwa_statiegeld_015",
                           '0.1' : "cwa_module.cwa_statiegeld_010",
                           '0.10' : "cwa_module.cwa_statiegeld_010",
                           '0.08' : "cwa_module.cwa_statiegeld_008",
                           }
